"""
Report assembler and pipeline orchestrator for Track B.

`run_pipeline()` runs all stages in sequence:
    Universe → Prices → Prefilter → Ranker → Thesis → Holdings diff → Report

The output is a dated markdown file saved to track_b/output/reports/.
Each stage caches its own results; re-running the same day is fast.
"""

import logging
from datetime import date, datetime
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

logger = logging.getLogger(__name__)

_CONFIG_PATH = Path(__file__).parent.parent.parent / "config.yaml"


# ── public API ────────────────────────────────────────────────────────────────

def run_pipeline(
    config: dict,
    force_refresh: bool = False,
) -> Path:
    """Run the full Track B pipeline and return the path to the saved report.

    Parameters
    ----------
    config        : parsed config.yaml
    force_refresh : bypass all caches and re-fetch everything

    Returns
    -------
    Path to the saved YYYY-MM-DD_report.md
    """
    from track_b.src.fetch import fetch_prices
    from track_b.src.holdings import format_recommendation, get_recommendation
    from track_b.src.prefilter import run_prefilter
    from track_b.src.ranker import run_ranker
    from track_b.src.thesis import generate_thesis
    from track_b.src.universe import load_universe

    started_at = datetime.now()
    logger.info("=== Track B pipeline starting (%s) ===", date.today())

    # 1. Universe
    universe = load_universe(config, force_refresh=force_refresh)
    logger.info("Stage 1/7 — Universe: %d tickers", len(universe))

    # 2. Prices
    tickers = universe["ticker"].tolist()
    closes, _volumes = fetch_prices(
        tickers, lookback_days=504, force_refresh=force_refresh
    )
    logger.info("Stage 2/7 — Prices: %d tickers × %d days", len(closes.columns), len(closes))

    # 3. Prefilter
    candidates = run_prefilter(universe, closes, _volumes, config)
    logger.info("Stage 3/7 — Prefilter: %d candidates", len(candidates))

    # 4. Ranker
    ranked = run_ranker(candidates, closes, config)
    logger.info("Stage 4/7 — Ranker: %d picks", len(ranked))

    if ranked.empty:
        raise RuntimeError("Ranker returned no candidates — cannot generate a pick.")

    # 5. Thesis
    pick = ranked.iloc[0]
    alternatives = ranked.iloc[1:]
    logger.info("Stage 5/7 — Thesis: generating for %s", pick.get("ticker"))
    thesis_text = generate_thesis(pick, alternatives, config)

    # 6. Holdings diff
    logger.info("Stage 6/7 — Holdings diff")
    rec = get_recommendation(pick, ranked, closes, config)
    holdings_md = format_recommendation(rec)

    # 7. Assemble + save
    elapsed = (datetime.now() - started_at).total_seconds()
    stats = {
        "universe_n":   len(universe),
        "prices_n":     len(closes.columns),
        "prefilter_n":  len(candidates),
        "ranker_n":     len(ranked),
        "elapsed_s":    elapsed,
    }
    report_md = _assemble(pick, ranked, thesis_text, holdings_md, stats)

    output_dir = Path(config["track_b"]["output"]["save_to"])
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / f"{date.today()}_report.md"
    report_path.write_text(report_md, encoding="utf-8")

    logger.info("Stage 7/7 — Report saved to %s (%.1fs total)", report_path, elapsed)
    return report_path


def load_config(path: Path | None = None) -> dict:
    """Load and return config.yaml."""
    p = path or _CONFIG_PATH
    with open(p, encoding="utf-8") as f:
        return yaml.safe_load(f)


# ── report assembly ───────────────────────────────────────────────────────────

def _assemble(
    pick: pd.Series,
    ranked: pd.DataFrame,
    thesis_text: str,
    holdings_md: str,
    stats: dict,
) -> str:
    ticker   = pick.get("ticker", "?")
    name     = pick.get("name", "")
    sector   = pick.get("sector", "")
    industry = pick.get("industry", "")
    today    = date.today()

    header = "\n".join([
        f"# Track B — Monthly Pick: {ticker}",
        f"*{today} · {name}*" + (f" · {sector} / {industry}" if sector else ""),
        "",
        "---",
        "",
    ])

    pipeline_section = "\n".join([
        "## Pipeline Summary",
        "",
        _pipeline_table(ranked),
        "",
        _pipeline_stats(stats),
    ])

    footer = (
        f"---\n\n"
        f"*Generated by Track B v0.1 · {today} · "
        f"Universe {stats['universe_n']:,} → "
        f"Prefilter {stats['prefilter_n']} → "
        f"Ranker {stats['ranker_n']} picks · "
        f"{stats['elapsed_s']:.0f}s*"
    )

    parts = [
        header,
        thesis_text,
        "",
        "---",
        "",
        holdings_md,
        "",
        "---",
        "",
        pipeline_section,
        "",
        footer,
    ]
    return "\n".join(parts)


def _pipeline_table(ranked: pd.DataFrame) -> str:
    """Markdown table of ranked candidates with key signals."""
    cols = {
        "ticker":          "Ticker",
        "name":            "Name",
        "composite_score": "Score",
        "forward_pe":      "Fwd PE",
        "revenue_growth":  "Rev Gr",
        "earnings_growth": "EPS Gr",
        "analyst_upside":  "Upside",
        "rsi_14":          "RSI",
        "momentum_12_1":   "Mom 12m",
    }

    header = "| # | " + " | ".join(cols.values()) + " |"
    sep    = "|---|" + "|".join(["---"] * len(cols)) + "|"
    rows   = [header, sep]

    for rank, (_, row) in enumerate(ranked.iterrows(), start=1):
        cells = [str(rank)]
        for col in cols:
            val = row.get(col)
            if col in ("revenue_growth", "earnings_growth", "analyst_upside", "momentum_12_1"):
                cells.append(_fmt_pct(val))
            elif col == "forward_pe":
                cells.append(_fmt_x(val))
            elif col in ("composite_score", "rsi_14"):
                cells.append(_fmt2(val))
            else:
                v = str(val) if pd.notna(val) and val != "" else "—"
                # truncate long names
                cells.append(v[:28] if col == "name" else v)
        rows.append("| " + " | ".join(cells) + " |")

    return "\n".join(rows)


def _pipeline_stats(stats: dict) -> str:
    return (
        f"*Universe scraped: {stats['universe_n']:,} names · "
        f"Prices loaded: {stats['prices_n']:,} tickers · "
        f"Prefilter output: {stats['prefilter_n']} · "
        f"Deep-dive output: {stats['ranker_n']}*"
    )


# ── formatting ────────────────────────────────────────────────────────────────

def _fmt_pct(val) -> str:
    try:
        f = float(val)
        return f"{f * 100:.1f}%" if np.isfinite(f) else "—"
    except (TypeError, ValueError):
        return "—"


def _fmt_x(val) -> str:
    try:
        f = float(val)
        return f"{f:.1f}x" if np.isfinite(f) else "—"
    except (TypeError, ValueError):
        return "—"


def _fmt2(val) -> str:
    try:
        f = float(val)
        return f"{f:.2f}" if np.isfinite(f) else "—"
    except (TypeError, ValueError):
        return "—"
